language: python
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - build-essential
    - automake
    - pkg-config
    - libtool
    - libffi-dev
    - libgmp-dev
matrix:
  include:
  - python: "3.5"
    env: TOX_ENV=flake8
  - python: "2.7"
    env: TOX_ENV=py27
  - python: "3.4"
    env: TOX_ENV=py34
  - python: "3.5"
    env: TOX_ENV=py35
  - python: "3.6"
    env: TOX_ENV=py36
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
